uploads = []

[[generated]]
id = "QSOjYab9bvDn71EdSS3DF"
uri = "file://artifacts/adam/assets/images/adam-boy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JBuruXjcxaCthvzryJ4bX"
uri = "file://artifacts/adam/assets/images/lulu-girl.png"
type = "image"
title = "generated_image"

[[generated]]
id = "H7A_sD_TYZOvMvxWwVVng"
uri = "file://artifacts/adam/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "qpJ9wv70z2TMtkx2Eo6hB"
uri = "file://my-hero-project.tar.gz"
type = "unspecified"
title = "My Hero – Audio Fully Fixed + Smaller Character"
