export type CountryEntry = {
  code: string;
  flag: string;
  name: string;
  nameAr: string;
  currency: string;
  symbol: string;
  rate: number; // USD multiplier
};

// prettier-ignore
export const COUNTRIES: CountryEntry[] = [
  { code: "AF", flag: "🇦🇫", name: "Afghanistan",                nameAr: "Afghanistan",           currency: "AFN", symbol: "؋",    rate: 70 },
  { code: "AL", flag: "🇦🇱", name: "Albania",                    nameAr: "Albania",               currency: "ALL", symbol: "L",    rate: 93 },
  { code: "DZ", flag: "🇩🇿", name: "Algeria",                    nameAr: "Algeria",               currency: "DZD", symbol: "DA",   rate: 134 },
  { code: "AD", flag: "🇦🇩", name: "Andorra",                    nameAr: "Andorra",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "AO", flag: "🇦🇴", name: "Angola",                     nameAr: "Angola",                currency: "AOA", symbol: "Kz",   rate: 850 },
  { code: "AG", flag: "🇦🇬", name: "Antigua & Barbuda",          nameAr: "Antigua & Barbuda",     currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "AR", flag: "🇦🇷", name: "Argentina",                  nameAr: "Argentina",             currency: "ARS", symbol: "$",    rate: 900 },
  { code: "AM", flag: "🇦🇲", name: "Armenia",                    nameAr: "Armenia",               currency: "AMD", symbol: "֏",    rate: 390 },
  { code: "AU", flag: "🇦🇺", name: "Australia",                  nameAr: "Australia",             currency: "AUD", symbol: "A$",   rate: 1.53 },
  { code: "AT", flag: "🇦🇹", name: "Austria",                    nameAr: "Austria",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "AZ", flag: "🇦🇿", name: "Azerbaijan",                 nameAr: "Azerbaijan",            currency: "AZN", symbol: "₼",    rate: 1.70 },
  { code: "BS", flag: "🇧🇸", name: "Bahamas",                    nameAr: "Bahamas",               currency: "BSD", symbol: "$",    rate: 1.00 },
  { code: "BH", flag: "🇧🇭", name: "Bahrain",                    nameAr: "Bahrain",               currency: "BHD", symbol: "BD",   rate: 0.38 },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh",                 nameAr: "Bangladesh",            currency: "BDT", symbol: "৳",    rate: 110 },
  { code: "BB", flag: "🇧🇧", name: "Barbados",                   nameAr: "Barbados",              currency: "BBD", symbol: "Bds$", rate: 2.00 },
  { code: "BY", flag: "🇧🇾", name: "Belarus",                    nameAr: "Belarus",               currency: "BYN", symbol: "Br",   rate: 3.24 },
  { code: "BE", flag: "🇧🇪", name: "Belgium",                    nameAr: "Belgium",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "BZ", flag: "🇧🇿", name: "Belize",                     nameAr: "Belize",                currency: "BZD", symbol: "BZ$",  rate: 2.00 },
  { code: "BJ", flag: "🇧🇯", name: "Benin",                      nameAr: "Benin",                 currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "BT", flag: "🇧🇹", name: "Bhutan",                     nameAr: "Bhutan",                currency: "BTN", symbol: "Nu",   rate: 83 },
  { code: "BO", flag: "🇧🇴", name: "Bolivia",                    nameAr: "Bolivia",               currency: "BOB", symbol: "Bs",   rate: 6.92 },
  { code: "BA", flag: "🇧🇦", name: "Bosnia & Herzegovina",       nameAr: "Bosnia",                currency: "BAM", symbol: "KM",   rate: 1.80 },
  { code: "BW", flag: "🇧🇼", name: "Botswana",                   nameAr: "Botswana",              currency: "BWP", symbol: "P",    rate: 13.5 },
  { code: "BR", flag: "🇧🇷", name: "Brazil",                     nameAr: "Brazil",                currency: "BRL", symbol: "R$",   rate: 5.10 },
  { code: "BN", flag: "🇧🇳", name: "Brunei",                     nameAr: "Brunei",                currency: "BND", symbol: "B$",   rate: 1.35 },
  { code: "BG", flag: "🇧🇬", name: "Bulgaria",                   nameAr: "Bulgaria",              currency: "BGN", symbol: "лв",   rate: 1.80 },
  { code: "BF", flag: "🇧🇫", name: "Burkina Faso",               nameAr: "Burkina Faso",          currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "BI", flag: "🇧🇮", name: "Burundi",                    nameAr: "Burundi",               currency: "BIF", symbol: "Fr",   rate: 2900 },
  { code: "CV", flag: "🇨🇻", name: "Cabo Verde",                 nameAr: "Cabo Verde",            currency: "CVE", symbol: "$",    rate: 101 },
  { code: "KH", flag: "🇰🇭", name: "Cambodia",                   nameAr: "Cambodia",              currency: "KHR", symbol: "៛",    rate: 4100 },
  { code: "CM", flag: "🇨🇲", name: "Cameroon",                   nameAr: "Cameroon",              currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "CA", flag: "🇨🇦", name: "Canada",                     nameAr: "Canada",                currency: "CAD", symbol: "C$",   rate: 1.36 },
  { code: "CF", flag: "🇨🇫", name: "Central African Republic",   nameAr: "Central African Rep.",  currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "TD", flag: "🇹🇩", name: "Chad",                       nameAr: "Chad",                  currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "CL", flag: "🇨🇱", name: "Chile",                      nameAr: "Chile",                 currency: "CLP", symbol: "$",    rate: 950 },
  { code: "CN", flag: "🇨🇳", name: "China",                      nameAr: "China",                 currency: "CNY", symbol: "¥",    rate: 7.24 },
  { code: "CO", flag: "🇨🇴", name: "Colombia",                   nameAr: "Colombia",              currency: "COP", symbol: "$",    rate: 4200 },
  { code: "KM", flag: "🇰🇲", name: "Comoros",                    nameAr: "Comoros",               currency: "KMF", symbol: "Fr",   rate: 450 },
  { code: "CG", flag: "🇨🇬", name: "Congo (Republic)",           nameAr: "Congo",                 currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "CD", flag: "🇨🇩", name: "Congo (DRC)",                nameAr: "DRC",                   currency: "CDF", symbol: "Fr",   rate: 2800 },
  { code: "CR", flag: "🇨🇷", name: "Costa Rica",                 nameAr: "Costa Rica",            currency: "CRC", symbol: "₡",    rate: 520 },
  { code: "HR", flag: "🇭🇷", name: "Croatia",                    nameAr: "Croatia",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "CU", flag: "🇨🇺", name: "Cuba",                       nameAr: "Cuba",                  currency: "CUP", symbol: "$",    rate: 24 },
  { code: "CY", flag: "🇨🇾", name: "Cyprus",                     nameAr: "Cyprus",                currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "CZ", flag: "🇨🇿", name: "Czech Republic",             nameAr: "Czech Republic",        currency: "CZK", symbol: "Kč",   rate: 23 },
  { code: "DK", flag: "🇩🇰", name: "Denmark",                    nameAr: "Denmark",               currency: "DKK", symbol: "kr",   rate: 6.90 },
  { code: "DJ", flag: "🇩🇯", name: "Djibouti",                   nameAr: "Djibouti",              currency: "DJF", symbol: "Fr",   rate: 178 },
  { code: "DM", flag: "🇩🇲", name: "Dominica",                   nameAr: "Dominica",              currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "DO", flag: "🇩🇴", name: "Dominican Republic",         nameAr: "Dominican Republic",    currency: "DOP", symbol: "$",    rate: 59 },
  { code: "EC", flag: "🇪🇨", name: "Ecuador",                    nameAr: "Ecuador",               currency: "USD", symbol: "$",    rate: 1 },
  { code: "EG", flag: "🇪🇬", name: "Egypt",                      nameAr: "Egypt",                 currency: "EGP", symbol: "E£",   rate: 49.5 },
  { code: "SV", flag: "🇸🇻", name: "El Salvador",                nameAr: "El Salvador",           currency: "USD", symbol: "$",    rate: 1 },
  { code: "GQ", flag: "🇬🇶", name: "Equatorial Guinea",          nameAr: "Equatorial Guinea",     currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "ER", flag: "🇪🇷", name: "Eritrea",                    nameAr: "Eritrea",               currency: "ERN", symbol: "Nkf",  rate: 15 },
  { code: "EE", flag: "🇪🇪", name: "Estonia",                    nameAr: "Estonia",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "SZ", flag: "🇸🇿", name: "Eswatini",                   nameAr: "Eswatini",              currency: "SZL", symbol: "L",    rate: 18.7 },
  { code: "ET", flag: "🇪🇹", name: "Ethiopia",                   nameAr: "Ethiopia",              currency: "ETB", symbol: "Br",   rate: 120 },
  { code: "FJ", flag: "🇫🇯", name: "Fiji",                       nameAr: "Fiji",                  currency: "FJD", symbol: "FJ$",  rate: 2.25 },
  { code: "FI", flag: "🇫🇮", name: "Finland",                    nameAr: "Finland",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "FR", flag: "🇫🇷", name: "France",                     nameAr: "France",                currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "GA", flag: "🇬🇦", name: "Gabon",                      nameAr: "Gabon",                 currency: "XAF", symbol: "CFA",  rate: 590 },
  { code: "GM", flag: "🇬🇲", name: "Gambia",                     nameAr: "Gambia",                currency: "GMD", symbol: "D",    rate: 67 },
  { code: "GE", flag: "🇬🇪", name: "Georgia",                    nameAr: "Georgia",               currency: "GEL", symbol: "₾",    rate: 2.70 },
  { code: "DE", flag: "🇩🇪", name: "Germany",                    nameAr: "Germany",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "GH", flag: "🇬🇭", name: "Ghana",                      nameAr: "Ghana",                 currency: "GHS", symbol: "₵",    rate: 15 },
  { code: "GR", flag: "🇬🇷", name: "Greece",                     nameAr: "Greece",                currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "GD", flag: "🇬🇩", name: "Grenada",                    nameAr: "Grenada",               currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "GT", flag: "🇬🇹", name: "Guatemala",                  nameAr: "Guatemala",             currency: "GTQ", symbol: "Q",    rate: 7.80 },
  { code: "GN", flag: "🇬🇳", name: "Guinea",                     nameAr: "Guinea",                currency: "GNF", symbol: "Fr",   rate: 8700 },
  { code: "GW", flag: "🇬🇼", name: "Guinea-Bissau",              nameAr: "Guinea-Bissau",         currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "GY", flag: "🇬🇾", name: "Guyana",                     nameAr: "Guyana",                currency: "GYD", symbol: "$",    rate: 210 },
  { code: "HT", flag: "🇭🇹", name: "Haiti",                      nameAr: "Haiti",                 currency: "HTG", symbol: "G",    rate: 133 },
  { code: "HN", flag: "🇭🇳", name: "Honduras",                   nameAr: "Honduras",              currency: "HNL", symbol: "L",    rate: 24.8 },
  { code: "HU", flag: "🇭🇺", name: "Hungary",                    nameAr: "Hungary",               currency: "HUF", symbol: "Ft",   rate: 360 },
  { code: "IS", flag: "🇮🇸", name: "Iceland",                    nameAr: "Iceland",               currency: "ISK", symbol: "kr",   rate: 139 },
  { code: "IN", flag: "🇮🇳", name: "India",                      nameAr: "India",                 currency: "INR", symbol: "₹",    rate: 83 },
  { code: "ID", flag: "🇮🇩", name: "Indonesia",                  nameAr: "Indonesia",             currency: "IDR", symbol: "Rp",   rate: 15600 },
  { code: "IR", flag: "🇮🇷", name: "Iran",                       nameAr: "Iran",                  currency: "IRR", symbol: "﷼",    rate: 42000 },
  { code: "IQ", flag: "🇮🇶", name: "Iraq",                       nameAr: "Iraq",                  currency: "IQD", symbol: "IQD",  rate: 1310 },
  { code: "IE", flag: "🇮🇪", name: "Ireland",                    nameAr: "Ireland",               currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "IL", flag: "🇮🇱", name: "Israel",                     nameAr: "Israel",                currency: "ILS", symbol: "₪",    rate: 3.71 },
  { code: "IT", flag: "🇮🇹", name: "Italy",                      nameAr: "Italy",                 currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "CI", flag: "🇨🇮", name: "Ivory Coast",                nameAr: "Ivory Coast",           currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "JM", flag: "🇯🇲", name: "Jamaica",                    nameAr: "Jamaica",               currency: "JMD", symbol: "J$",   rate: 155 },
  { code: "JP", flag: "🇯🇵", name: "Japan",                      nameAr: "Japan",                 currency: "JPY", symbol: "¥",    rate: 150 },
  { code: "JO", flag: "🇯🇴", name: "Jordan",                     nameAr: "Jordan",                currency: "JOD", symbol: "JD",   rate: 0.71 },
  { code: "KZ", flag: "🇰🇿", name: "Kazakhstan",                 nameAr: "Kazakhstan",            currency: "KZT", symbol: "₸",    rate: 450 },
  { code: "KE", flag: "🇰🇪", name: "Kenya",                      nameAr: "Kenya",                 currency: "KES", symbol: "Ksh",  rate: 128 },
  { code: "KI", flag: "🇰🇮", name: "Kiribati",                   nameAr: "Kiribati",              currency: "AUD", symbol: "A$",   rate: 1.53 },
  { code: "KW", flag: "🇰🇼", name: "Kuwait",                     nameAr: "Kuwait",                currency: "KWD", symbol: "KD",   rate: 0.31 },
  { code: "KG", flag: "🇰🇬", name: "Kyrgyzstan",                 nameAr: "Kyrgyzstan",            currency: "KGS", symbol: "с",    rate: 88 },
  { code: "LA", flag: "🇱🇦", name: "Laos",                       nameAr: "Laos",                  currency: "LAK", symbol: "₭",    rate: 21000 },
  { code: "LV", flag: "🇱🇻", name: "Latvia",                     nameAr: "Latvia",                currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "LB", flag: "🇱🇧", name: "Lebanon",                    nameAr: "Lebanon",               currency: "USD", symbol: "$",    rate: 1 },
  { code: "LS", flag: "🇱🇸", name: "Lesotho",                    nameAr: "Lesotho",               currency: "LSL", symbol: "L",    rate: 18.7 },
  { code: "LR", flag: "🇱🇷", name: "Liberia",                    nameAr: "Liberia",               currency: "LRD", symbol: "L$",   rate: 190 },
  { code: "LY", flag: "🇱🇾", name: "Libya",                      nameAr: "Libya",                 currency: "LYD", symbol: "LD",   rate: 4.83 },
  { code: "LI", flag: "🇱🇮", name: "Liechtenstein",              nameAr: "Liechtenstein",         currency: "CHF", symbol: "Fr",   rate: 0.90 },
  { code: "LT", flag: "🇱🇹", name: "Lithuania",                  nameAr: "Lithuania",             currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "LU", flag: "🇱🇺", name: "Luxembourg",                 nameAr: "Luxembourg",            currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "MG", flag: "🇲🇬", name: "Madagascar",                 nameAr: "Madagascar",            currency: "MGA", symbol: "Ar",   rate: 4500 },
  { code: "MW", flag: "🇲🇼", name: "Malawi",                     nameAr: "Malawi",                currency: "MWK", symbol: "MK",   rate: 1700 },
  { code: "MY", flag: "🇲🇾", name: "Malaysia",                   nameAr: "Malaysia",              currency: "MYR", symbol: "RM",   rate: 4.73 },
  { code: "MV", flag: "🇲🇻", name: "Maldives",                   nameAr: "Maldives",              currency: "MVR", symbol: "Rf",   rate: 15.4 },
  { code: "ML", flag: "🇲🇱", name: "Mali",                       nameAr: "Mali",                  currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "MT", flag: "🇲🇹", name: "Malta",                      nameAr: "Malta",                 currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "MH", flag: "🇲🇭", name: "Marshall Islands",           nameAr: "Marshall Islands",      currency: "USD", symbol: "$",    rate: 1 },
  { code: "MR", flag: "🇲🇷", name: "Mauritania",                 nameAr: "Mauritania",            currency: "MRU", symbol: "UM",   rate: 38 },
  { code: "MU", flag: "🇲🇺", name: "Mauritius",                  nameAr: "Mauritius",             currency: "MUR", symbol: "Rs",   rate: 45 },
  { code: "MX", flag: "🇲🇽", name: "Mexico",                     nameAr: "Mexico",                currency: "MXN", symbol: "$",    rate: 17 },
  { code: "FM", flag: "🇫🇲", name: "Micronesia",                 nameAr: "Micronesia",            currency: "USD", symbol: "$",    rate: 1 },
  { code: "MD", flag: "🇲🇩", name: "Moldova",                    nameAr: "Moldova",               currency: "MDL", symbol: "L",    rate: 17.7 },
  { code: "MC", flag: "🇲🇨", name: "Monaco",                     nameAr: "Monaco",                currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "MN", flag: "🇲🇳", name: "Mongolia",                   nameAr: "Mongolia",              currency: "MNT", symbol: "₮",    rate: 3400 },
  { code: "ME", flag: "🇲🇪", name: "Montenegro",                 nameAr: "Montenegro",            currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "MA", flag: "🇲🇦", name: "Morocco",                    nameAr: "Morocco",               currency: "MAD", symbol: "MAD",  rate: 9.97 },
  { code: "MZ", flag: "🇲🇿", name: "Mozambique",                 nameAr: "Mozambique",            currency: "MZN", symbol: "MT",   rate: 63.8 },
  { code: "MM", flag: "🇲🇲", name: "Myanmar",                    nameAr: "Myanmar",               currency: "MMK", symbol: "K",    rate: 2100 },
  { code: "NA", flag: "🇳🇦", name: "Namibia",                    nameAr: "Namibia",               currency: "NAD", symbol: "N$",   rate: 18.7 },
  { code: "NR", flag: "🇳🇷", name: "Nauru",                      nameAr: "Nauru",                 currency: "AUD", symbol: "A$",   rate: 1.53 },
  { code: "NP", flag: "🇳🇵", name: "Nepal",                      nameAr: "Nepal",                 currency: "NPR", symbol: "Rs",   rate: 133 },
  { code: "NL", flag: "🇳🇱", name: "Netherlands",                nameAr: "Netherlands",           currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand",                nameAr: "New Zealand",           currency: "NZD", symbol: "NZ$",  rate: 1.62 },
  { code: "NI", flag: "🇳🇮", name: "Nicaragua",                  nameAr: "Nicaragua",             currency: "NIO", symbol: "C$",   rate: 36.8 },
  { code: "NE", flag: "🇳🇪", name: "Niger",                      nameAr: "Niger",                 currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "NG", flag: "🇳🇬", name: "Nigeria",                    nameAr: "Nigeria",               currency: "NGN", symbol: "₦",    rate: 1550 },
  { code: "MK", flag: "🇲🇰", name: "North Macedonia",            nameAr: "North Macedonia",       currency: "MKD", symbol: "ден",  rate: 56.8 },
  { code: "NO", flag: "🇳🇴", name: "Norway",                     nameAr: "Norway",                currency: "NOK", symbol: "kr",   rate: 10.6 },
  { code: "OM", flag: "🇴🇲", name: "Oman",                       nameAr: "Oman",                  currency: "OMR", symbol: "RO",   rate: 0.39 },
  { code: "PK", flag: "🇵🇰", name: "Pakistan",                   nameAr: "Pakistan",              currency: "PKR", symbol: "Rs",   rate: 278 },
  { code: "PW", flag: "🇵🇼", name: "Palau",                      nameAr: "Palau",                 currency: "USD", symbol: "$",    rate: 1 },
  { code: "PS", flag: "🇵🇸", name: "Palestine",                  nameAr: "Palestine",             currency: "USD", symbol: "$",    rate: 1 },
  { code: "PA", flag: "🇵🇦", name: "Panama",                     nameAr: "Panama",                currency: "PAB", symbol: "B/.",  rate: 1 },
  { code: "PG", flag: "🇵🇬", name: "Papua New Guinea",           nameAr: "Papua New Guinea",      currency: "PGK", symbol: "K",    rate: 3.80 },
  { code: "PY", flag: "🇵🇾", name: "Paraguay",                   nameAr: "Paraguay",              currency: "PYG", symbol: "₲",    rate: 7600 },
  { code: "PE", flag: "🇵🇪", name: "Peru",                       nameAr: "Peru",                  currency: "PEN", symbol: "S/",   rate: 3.72 },
  { code: "PH", flag: "🇵🇭", name: "Philippines",                nameAr: "Philippines",           currency: "PHP", symbol: "₱",    rate: 56 },
  { code: "PL", flag: "🇵🇱", name: "Poland",                     nameAr: "Poland",                currency: "PLN", symbol: "zł",   rate: 4.04 },
  { code: "PT", flag: "🇵🇹", name: "Portugal",                   nameAr: "Portugal",              currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "QA", flag: "🇶🇦", name: "Qatar",                      nameAr: "Qatar",                 currency: "QAR", symbol: "QR",   rate: 3.64 },
  { code: "RO", flag: "🇷🇴", name: "Romania",                    nameAr: "Romania",               currency: "RON", symbol: "lei",  rate: 4.57 },
  { code: "RU", flag: "🇷🇺", name: "Russia",                     nameAr: "Russia",                currency: "RUB", symbol: "₽",    rate: 90 },
  { code: "RW", flag: "🇷🇼", name: "Rwanda",                     nameAr: "Rwanda",                currency: "RWF", symbol: "Fr",   rate: 1290 },
  { code: "KN", flag: "🇰🇳", name: "Saint Kitts & Nevis",        nameAr: "Saint Kitts & Nevis",   currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "LC", flag: "🇱🇨", name: "Saint Lucia",                nameAr: "Saint Lucia",           currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "VC", flag: "🇻🇨", name: "Saint Vincent & Grenadines", nameAr: "Saint Vincent",         currency: "XCD", symbol: "EC$",  rate: 2.70 },
  { code: "WS", flag: "🇼🇸", name: "Samoa",                      nameAr: "Samoa",                 currency: "WST", symbol: "T",    rate: 2.77 },
  { code: "SM", flag: "🇸🇲", name: "San Marino",                 nameAr: "San Marino",            currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "ST", flag: "🇸🇹", name: "Sao Tome & Principe",        nameAr: "Sao Tome & Principe",   currency: "STN", symbol: "Db",   rate: 22.6 },
  { code: "SA", flag: "🇸🇦", name: "Saudi Arabia",               nameAr: "Saudi Arabia",          currency: "SAR", symbol: "SR",   rate: 3.75 },
  { code: "SN", flag: "🇸🇳", name: "Senegal",                    nameAr: "Senegal",               currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "RS", flag: "🇷🇸", name: "Serbia",                     nameAr: "Serbia",                currency: "RSD", symbol: "din",  rate: 108 },
  { code: "SC", flag: "🇸🇨", name: "Seychelles",                 nameAr: "Seychelles",            currency: "SCR", symbol: "Rs",   rate: 13.6 },
  { code: "SL", flag: "🇸🇱", name: "Sierra Leone",               nameAr: "Sierra Leone",          currency: "SLE", symbol: "Le",   rate: 22 },
  { code: "SG", flag: "🇸🇬", name: "Singapore",                  nameAr: "Singapore",             currency: "SGD", symbol: "S$",   rate: 1.35 },
  { code: "SK", flag: "🇸🇰", name: "Slovakia",                   nameAr: "Slovakia",              currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "SI", flag: "🇸🇮", name: "Slovenia",                   nameAr: "Slovenia",              currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "SB", flag: "🇸🇧", name: "Solomon Islands",            nameAr: "Solomon Islands",       currency: "SBD", symbol: "SI$",  rate: 8.43 },
  { code: "SO", flag: "🇸🇴", name: "Somalia",                    nameAr: "Somalia",               currency: "SOS", symbol: "Sh",   rate: 571 },
  { code: "ZA", flag: "🇿🇦", name: "South Africa",               nameAr: "South Africa",          currency: "ZAR", symbol: "R",    rate: 18.7 },
  { code: "KR", flag: "🇰🇷", name: "South Korea",                nameAr: "South Korea",           currency: "KRW", symbol: "₩",    rate: 1330 },
  { code: "SS", flag: "🇸🇸", name: "South Sudan",                nameAr: "South Sudan",           currency: "SSP", symbol: "£",    rate: 130 },
  { code: "ES", flag: "🇪🇸", name: "Spain",                      nameAr: "Spain",                 currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "LK", flag: "🇱🇰", name: "Sri Lanka",                  nameAr: "Sri Lanka",             currency: "LKR", symbol: "Rs",   rate: 310 },
  { code: "SD", flag: "🇸🇩", name: "Sudan",                      nameAr: "Sudan",                 currency: "SDG", symbol: "SDG",  rate: 601 },
  { code: "SR", flag: "🇸🇷", name: "Suriname",                   nameAr: "Suriname",              currency: "SRD", symbol: "$",    rate: 36.5 },
  { code: "SE", flag: "🇸🇪", name: "Sweden",                     nameAr: "Sweden",                currency: "SEK", symbol: "kr",   rate: 10.4 },
  { code: "CH", flag: "🇨🇭", name: "Switzerland",                nameAr: "Switzerland",           currency: "CHF", symbol: "Fr",   rate: 0.90 },
  { code: "SY", flag: "🇸🇾", name: "Syria",                      nameAr: "Syria",                 currency: "SYP", symbol: "LS",   rate: 12900 },
  { code: "TW", flag: "🇹🇼", name: "Taiwan",                     nameAr: "Taiwan",                currency: "TWD", symbol: "NT$",  rate: 31.9 },
  { code: "TJ", flag: "🇹🇯", name: "Tajikistan",                 nameAr: "Tajikistan",            currency: "TJS", symbol: "SM",   rate: 10.9 },
  { code: "TZ", flag: "🇹🇿", name: "Tanzania",                   nameAr: "Tanzania",              currency: "TZS", symbol: "Sh",   rate: 2700 },
  { code: "TH", flag: "🇹🇭", name: "Thailand",                   nameAr: "Thailand",              currency: "THB", symbol: "฿",    rate: 35.5 },
  { code: "TL", flag: "🇹🇱", name: "Timor-Leste",                nameAr: "Timor-Leste",           currency: "USD", symbol: "$",    rate: 1 },
  { code: "TG", flag: "🇹🇬", name: "Togo",                       nameAr: "Togo",                  currency: "XOF", symbol: "CFA",  rate: 590 },
  { code: "TO", flag: "🇹🇴", name: "Tonga",                      nameAr: "Tonga",                 currency: "TOP", symbol: "T$",   rate: 2.35 },
  { code: "TT", flag: "🇹🇹", name: "Trinidad & Tobago",          nameAr: "Trinidad & Tobago",     currency: "TTD", symbol: "TT$",  rate: 6.78 },
  { code: "TN", flag: "🇹🇳", name: "Tunisia",                    nameAr: "Tunisia",               currency: "TND", symbol: "DT",   rate: 3.12 },
  { code: "TR", flag: "🇹🇷", name: "Turkey",                     nameAr: "Turkey",                currency: "TRY", symbol: "₺",    rate: 34 },
  { code: "TM", flag: "🇹🇲", name: "Turkmenistan",               nameAr: "Turkmenistan",          currency: "TMT", symbol: "T",    rate: 3.50 },
  { code: "TV", flag: "🇹🇻", name: "Tuvalu",                     nameAr: "Tuvalu",                currency: "AUD", symbol: "A$",   rate: 1.53 },
  { code: "UG", flag: "🇺🇬", name: "Uganda",                     nameAr: "Uganda",                currency: "UGX", symbol: "Sh",   rate: 3800 },
  { code: "UA", flag: "🇺🇦", name: "Ukraine",                    nameAr: "Ukraine",               currency: "UAH", symbol: "₴",    rate: 38.5 },
  { code: "AE", flag: "🇦🇪", name: "United Arab Emirates",       nameAr: "United Arab Emirates",  currency: "AED", symbol: "AED",  rate: 3.67 },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom",             nameAr: "United Kingdom",        currency: "GBP", symbol: "£",    rate: 0.79 },
  { code: "US", flag: "🇺🇸", name: "United States",              nameAr: "United States",         currency: "USD", symbol: "$",    rate: 1 },
  { code: "UY", flag: "🇺🇾", name: "Uruguay",                    nameAr: "Uruguay",               currency: "UYU", symbol: "$U",   rate: 39 },
  { code: "UZ", flag: "🇺🇿", name: "Uzbekistan",                 nameAr: "Uzbekistan",            currency: "UZS", symbol: "soʻm", rate: 12700 },
  { code: "VU", flag: "🇻🇺", name: "Vanuatu",                    nameAr: "Vanuatu",               currency: "VUV", symbol: "VT",   rate: 119 },
  { code: "VA", flag: "🇻🇦", name: "Vatican City",               nameAr: "Vatican City",          currency: "EUR", symbol: "€",    rate: 0.92 },
  { code: "VE", flag: "🇻🇪", name: "Venezuela",                  nameAr: "Venezuela",             currency: "VES", symbol: "Bs",   rate: 36 },
  { code: "VN", flag: "🇻🇳", name: "Vietnam",                    nameAr: "Vietnam",               currency: "VND", symbol: "₫",    rate: 24500 },
  { code: "YE", flag: "🇾🇪", name: "Yemen",                      nameAr: "Yemen",                 currency: "YER", symbol: "YR",   rate: 250 },
  { code: "ZM", flag: "🇿🇲", name: "Zambia",                     nameAr: "Zambia",                currency: "ZMW", symbol: "ZK",   rate: 27 },
  { code: "ZW", flag: "🇿🇼", name: "Zimbabwe",                   nameAr: "Zimbabwe",              currency: "USD", symbol: "$",    rate: 1 },
];

export function convertPrice(usdPrice: number, rate: number, symbol: string): string {
  const local = usdPrice * rate;
  if (local < 10) return `${symbol}${local.toFixed(2)}`;
  if (local < 100) return `${symbol}${Math.round(local)}`;
  return `${symbol}${Math.round(local).toLocaleString()}`;
}

export const PLANS_USD = {
  monthly:  { usd: 24.99,  label: "Monthly",  labelAr: "شهري" },
  biannual: { usd: 135.99, label: "6 Months", labelAr: "٦ أشهر", savePct: 10 },
  yearly:   { usd: 236.99, label: "Yearly",   labelAr: "سنوي",   savePct: 21 },
};
