import type { Lang } from "./i18n";

// Word Puzzle — 50+ words per language
export const puzzleWords: Record<
  Lang,
  Array<{ emoji: string; word: string }>
> = {
  en: [
    { emoji: "🐱", word: "CAT" },
    { emoji: "🐶", word: "DOG" },
    { emoji: "☀️", word: "SUN" },
    { emoji: "🚗", word: "CAR" },
    { emoji: "🍎", word: "APPLE" },
    { emoji: "🏠", word: "HOUSE" },
    { emoji: "📖", word: "BOOK" },
    { emoji: "⭐", word: "STAR" },
    { emoji: "🐠", word: "FISH" },
    { emoji: "🌈", word: "RAINBOW" },
    { emoji: "🐰", word: "RABBIT" },
    { emoji: "🌙", word: "MOON" },
    { emoji: "🌊", word: "WAVE" },
    { emoji: "🍕", word: "PIZZA" },
    { emoji: "🎈", word: "BALLOON" },
    { emoji: "🦁", word: "LION" },
    { emoji: "🐘", word: "ELEPHANT" },
    { emoji: "🍓", word: "STRAWBERRY" },
    { emoji: "✈️", word: "PLANE" },
    { emoji: "🚂", word: "TRAIN" },
    { emoji: "⚽", word: "BALL" },
    { emoji: "🎵", word: "MUSIC" },
    { emoji: "🌺", word: "FLOWER" },
    { emoji: "🦋", word: "BUTTERFLY" },
    { emoji: "🐢", word: "TURTLE" },
    { emoji: "🍦", word: "ICECREAM" },
    { emoji: "🎨", word: "PAINT" },
    { emoji: "🏄", word: "SURF" },
    { emoji: "🌍", word: "EARTH" },
    { emoji: "🦊", word: "FOX" },
    { emoji: "🧁", word: "CUPCAKE" },
    { emoji: "🎯", word: "TARGET" },
    { emoji: "🦈", word: "SHARK" },
    { emoji: "🐬", word: "DOLPHIN" },
    { emoji: "🌵", word: "CACTUS" },
    { emoji: "🏔️", word: "MOUNTAIN" },
    { emoji: "🎸", word: "GUITAR" },
    { emoji: "🍊", word: "ORANGE" },
    { emoji: "🦜", word: "PARROT" },
    { emoji: "🐻", word: "BEAR" },
    { emoji: "🍇", word: "GRAPES" },
    { emoji: "🐙", word: "OCTOPUS" },
    { emoji: "🌻", word: "SUNFLOWER" },
    { emoji: "🦀", word: "CRAB" },
    { emoji: "🎃", word: "PUMPKIN" },
    { emoji: "🌮", word: "TACO" },
    { emoji: "🧩", word: "PUZZLE" },
    { emoji: "🎠", word: "CAROUSEL" },
    { emoji: "🦒", word: "GIRAFFE" },
    { emoji: "🐊", word: "CROCODILE" },
  ],
  ar: [
    { emoji: "🐱", word: "قطة" },
    { emoji: "🐶", word: "كلب" },
    { emoji: "☀️", word: "شمس" },
    { emoji: "🚗", word: "سيارة" },
    { emoji: "🍎", word: "تفاح" },
    { emoji: "🏠", word: "بيت" },
    { emoji: "📖", word: "كتاب" },
    { emoji: "⭐", word: "نجمة" },
    { emoji: "🌙", word: "قمر" },
    { emoji: "🐘", word: "فيل" },
    { emoji: "🦁", word: "أسد" },
    { emoji: "🐠", word: "سمكة" },
    { emoji: "🌹", word: "وردة" },
    { emoji: "🍊", word: "برتقال" },
    { emoji: "🍓", word: "فراولة" },
    { emoji: "🐢", word: "سلحفاة" },
    { emoji: "✈️", word: "طائرة" },
    { emoji: "🚂", word: "قطار" },
    { emoji: "⚽", word: "كرة" },
    { emoji: "🏔️", word: "جبل" },
    { emoji: "🌊", word: "موجة" },
    { emoji: "🎈", word: "بالون" },
    { emoji: "🐬", word: "دولفين" },
    { emoji: "🦋", word: "فراشة" },
    { emoji: "🌵", word: "صبار" },
    { emoji: "🍇", word: "عنب" },
    { emoji: "🐻", word: "دب" },
    { emoji: "🦊", word: "ثعلب" },
    { emoji: "🐙", word: "أخطبوط" },
    { emoji: "🌻", word: "دوار" },
    { emoji: "🎸", word: "قيثارة" },
    { emoji: "🦒", word: "زرافة" },
    { emoji: "🐊", word: "تمساح" },
    { emoji: "🍦", word: "بوظة" },
    { emoji: "🧁", word: "كعكة" },
    { emoji: "🎃", word: "قرعة" },
    { emoji: "🌮", word: "طاكو" },
    { emoji: "🦈", word: "قرش" },
    { emoji: "🐬", word: "دلفين" },
    { emoji: "🌺", word: "زهرة" },
    { emoji: "🎵", word: "موسيقى" },
    { emoji: "🌍", word: "كرة أرضية" },
    { emoji: "🏄", word: "تزلج" },
    { emoji: "🦜", word: "ببغاء" },
    { emoji: "🎨", word: "رسم" },
    { emoji: "🎯", word: "هدف" },
    { emoji: "🐰", word: "أرنب" },
    { emoji: "🍕", word: "بيتزا" },
    { emoji: "🎠", word: "حلقة" },
  ],
};

// Letter match — full English alphabet (A–Z) and Arabic alphabet
export const letterMatchPairs: Record<
  Lang,
  Array<{ letter: string; emoji: string; word: string }>
> = {
  en: [
    { letter: "A", emoji: "🍎", word: "Apple" },
    { letter: "B", emoji: "🐝", word: "Bee" },
    { letter: "C", emoji: "🐱", word: "Cat" },
    { letter: "D", emoji: "🐶", word: "Dog" },
    { letter: "E", emoji: "🐘", word: "Elephant" },
    { letter: "F", emoji: "🐟", word: "Fish" },
    { letter: "G", emoji: "🦒", word: "Giraffe" },
    { letter: "H", emoji: "🏠", word: "House" },
    { letter: "I", emoji: "🍦", word: "Icecream" },
    { letter: "J", emoji: "🕹️", word: "Joystick" },
    { letter: "K", emoji: "🪁", word: "Kite" },
    { letter: "L", emoji: "🦁", word: "Lion" },
    { letter: "M", emoji: "🌙", word: "Moon" },
    { letter: "N", emoji: "🌙", word: "Night" },
    { letter: "O", emoji: "🐙", word: "Octopus" },
    { letter: "P", emoji: "🐧", word: "Penguin" },
    { letter: "Q", emoji: "👑", word: "Queen" },
    { letter: "R", emoji: "🌈", word: "Rainbow" },
    { letter: "S", emoji: "☀️", word: "Sun" },
    { letter: "T", emoji: "🐢", word: "Turtle" },
    { letter: "U", emoji: "☂️", word: "Umbrella" },
    { letter: "V", emoji: "🎻", word: "Violin" },
    { letter: "W", emoji: "🌊", word: "Wave" },
    { letter: "X", emoji: "🎸", word: "Xylophone" },
    { letter: "Y", emoji: "⛵", word: "Yacht" },
    { letter: "Z", emoji: "🦓", word: "Zebra" },
  ],
  ar: [
    { letter: "أ", emoji: "🦁", word: "أسد" },
    { letter: "ب", emoji: "🐚", word: "بحر" },
    { letter: "ت", emoji: "🍎", word: "تفاحة" },
    { letter: "ث", emoji: "🐍", word: "ثعبان" },
    { letter: "ج", emoji: "🐫", word: "جمل" },
    { letter: "ح", emoji: "🐎", word: "حصان" },
    { letter: "خ", emoji: "🗡️", word: "خنجر" },
    { letter: "د", emoji: "🐻", word: "دب" },
    { letter: "ذ", emoji: "🦊", word: "ذئب" },
    { letter: "ر", emoji: "🍇", word: "رمان" },
    { letter: "ز", emoji: "🌸", word: "زهرة" },
    { letter: "س", emoji: "🐟", word: "سمكة" },
    { letter: "ش", emoji: "☀️", word: "شمس" },
    { letter: "ص", emoji: "🦅", word: "صقر" },
    { letter: "ض", emoji: "🐊", word: "ضفدع" },
    { letter: "ط", emoji: "✈️", word: "طائرة" },
    { letter: "ظ", emoji: "🦌", word: "ظبي" },
    { letter: "ع", emoji: "🍇", word: "عنب" },
    { letter: "غ", emoji: "🌊", word: "غيمة" },
    { letter: "ف", emoji: "🦋", word: "فراشة" },
    { letter: "ق", emoji: "🌙", word: "قمر" },
    { letter: "ك", emoji: "📖", word: "كتاب" },
    { letter: "ل", emoji: "🌸", word: "لوز" },
    { letter: "م", emoji: "🌊", word: "موج" },
    { letter: "ن", emoji: "⭐", word: "نجمة" },
    { letter: "هـ", emoji: "🐱", word: "هرة" },
    { letter: "و", word: "وردة", emoji: "🌹" },
    { letter: "ي", emoji: "🤝", word: "يد" },
  ],
};

// Math Blast levels — 5 clear levels
export type MathLevel = {
  id: number;
  labelEn: string;
  labelAr: string;
  ops: ("+" | "-" | "×" | "÷")[];
  maxNum: number;
  questionsPerLevel: number;
};

export const mathLevels: MathLevel[] = [
  { id: 1, labelEn: "Level 1 — Adding to 10", labelAr: "المستوى ١ — جمع إلى ١٠", ops: ["+"], maxNum: 10, questionsPerLevel: 5 },
  { id: 2, labelEn: "Level 2 — Adding to 20", labelAr: "المستوى ٢ — جمع إلى ٢٠", ops: ["+", "-"], maxNum: 20, questionsPerLevel: 5 },
  { id: 3, labelEn: "Level 3 — Subtraction", labelAr: "المستوى ٣ — طرح", ops: ["+", "-"], maxNum: 30, questionsPerLevel: 6 },
  { id: 4, labelEn: "Level 4 — Multiplication", labelAr: "المستوى ٤ — ضرب", ops: ["+", "-", "×"], maxNum: 12, questionsPerLevel: 6 },
  { id: 5, labelEn: "Level 5 — Champion!", labelAr: "المستوى ٥ — البطولة!", ops: ["+", "-", "×"], maxNum: 20, questionsPerLevel: 8 },
];

// Jigsaw puzzles — expanded to 6 puzzles
export const jigsawImages = [
  { id: "solar", emojiCenter: "🪐", titleEn: "Solar System", titleAr: "النظام الشمسي", funEn: "Did you know Jupiter is SO big 1,300 Earths could fit inside it?! 🪐", funAr: "هل تعلم أن المشتري ضخم لدرجة أن ١٣٠٠ كرة أرضية تنحط جواه؟! 🪐" },
  { id: "world", emojiCenter: "🌍", titleEn: "World Map", titleAr: "خريطة العالم", funEn: "Earth is moving 107,000 km/h around the sun RIGHT NOW! 🚀", funAr: "الأرض تتحرك ١٠٧ ألف كم/ساعة حول الشمس الآن! 🚀" },
  { id: "abc", emojiCenter: "🔠", titleEn: "English Alphabet", titleAr: "الأبجدية", funEn: "There are 26 English letters — you know them all! 🔠", funAr: "في ٢٦ حرف إنجليزي و ٢٨ حرف عربي! 🔠" },
  { id: "ocean", emojiCenter: "🌊", titleEn: "Ocean Life", titleAr: "حياة البحر", funEn: "The ocean covers 71% of the Earth's surface! 🌊", funAr: "المحيطات تغطي ٧١٪ من سطح الأرض! 🌊" },
  { id: "jungle", emojiCenter: "🌴", titleEn: "Jungle Animals", titleAr: "حيوانات الغابة", funEn: "There are more species in a jungle than anywhere on Earth! 🌴", funAr: "الغابة الاستوائية فيها أكثر أنواع حيوانات من أي مكان بالأرض! 🌴" },
  { id: "space", emojiCenter: "🚀", titleEn: "Space Adventure", titleAr: "مغامرة الفضاء", funEn: "It takes 8 minutes for sunlight to reach Earth! ☀️", funAr: "يستغرق ضوء الشمس ٨ دقائق ليصل للأرض! ☀️" },
];
