export type Story = {
  id: string;
  lang: "en";
  titleEn: string;
  emoji: string;
  moral: string;
  sentences: string[];
};

export const STORIES: Story[] = [
  {
    id: "1",
    lang: "en",
    titleEn: "The Girl Who Never Stopped Trying",
    emoji: "💡",
    moral: "Every mistake is a step closer to your answer.",
    sentences: [
      "Layla was eight years old, and she had one big dream: to make a light bulb glow using only a lemon from her grandmother's garden.",
      "Every afternoon after school, she spread her notebook on the kitchen table, lined up her copper clips and wires, and placed three lemons in a row.",
      "Her first experiment failed completely. The bulb stayed cold and dark no matter how many times she checked.",
      "She wrote in her notebook: Experiment one — did not work. The wire was too thin. Tomorrow I will try something thicker.",
      "Her second try failed. So did her third and her fourth.",
      "Her older brother came in and said: Give up, Layla. Lemons are for lemonade, not for science!",
      "Layla looked at her notes calmly and said: Thomas Edison failed more than a thousand times before he made the light bulb. I have only failed four times.",
      "On her seventh experiment, she pressed a copper coin and a zinc clip into the lemon, connected the wires very carefully, and held her breath.",
      "A tiny, soft golden light blinked on.",
      "Layla sat very still for a long moment — then laughed so loudly that her mother came running from the next room.",
      "Her mother held Layla's face gently and said: You did not succeed because you were clever. You succeeded because you refused to stop.",
      "That night, Layla wrote on the very last page of her notebook in the biggest letters she could: Every mistake is a step closer to your answer.",
      "She kept learning — about batteries, circuits, and solar energy. She won three science competitions.",
      "Many years later, Layla led a team of engineers who brought electricity to twelve villages in the desert, where children finally did their homework under electric light — and on her desk, she always kept that small lemon notebook.",
    ],
  },
  {
    id: "2",
    lang: "en",
    titleEn: "The Boy Who Talked to Trees",
    emoji: "🌳",
    moral: "The earth is always listening. Protect what you love before it is gone.",
    sentences: [
      "Idris was ten years old and had a habit that made his classmates laugh: he talked to trees.",
      "Every morning on his way to school, he stopped at the oldest oak in the neighborhood, placed his hand on its bark, and said: Good morning. Are you growing today?",
      "His friends thought it was silly. Trees cannot hear you, they said.",
      "But Idris had read that plants respond to sound and vibration, and he believed that listening — even to something that cannot speak back — was a form of respect.",
      "One spring, the city decided to cut down the old oak tree to widen the road.",
      "Idris felt something break inside him. That tree had stood in that spot for more than sixty years.",
      "He did not shout or cry. Instead, he went home and wrote a careful letter to the city council, full of facts about how trees clean the air, cool streets, and protect neighborhoods from floods.",
      "He collected forty-three signatures from neighbors and asked his teacher to help him present the letter at a local meeting.",
      "The council listened carefully. They decided to reroute the road and spare the tree.",
      "The old oak still stands today, with a small sign beside it that reads: Protected by the community.",
      "Idris's mother asked him: How did you know what to do?",
      "He said: I learned it from the tree. It stood there for sixty years, quietly giving shade and clean air to everyone, without ever asking for anything. I just tried to do the same.",
      "And that day, Idris understood something he would carry his whole life: the earth is always listening — and it is up to us to listen back.",
    ],
  },
  {
    id: "3",
    lang: "en",
    titleEn: "Two Seeds in the Same Garden",
    emoji: "🤝",
    moral: "When you help someone else grow, you always grow too.",
    sentences: [
      "Maya and Rowan were neighbors and best friends, but they argued about one thing: whose garden vegetables grew better.",
      "Maya's family planted tomatoes, and Rowan's family planted cucumbers, and every summer both families competed to grow the most beautiful harvest.",
      "One summer, a long dry spell hit their neighborhood. The sun beat down without mercy, and the wells ran low.",
      "Maya's tomato plants began to wilt. Rowan's cucumber plants also struggled to survive.",
      "One afternoon, both children sat at the fence between their gardens, feeling defeated.",
      "Rowan said: My cucumbers need shade. The sun is burning them.",
      "Maya said: My tomatoes need more water. The soil dries out too fast.",
      "They looked at each other — and then, at exactly the same time, they both had the same idea.",
      "What if the cucumber vines climbed Maya's fence and gave shade to the tomatoes? And what if the tomato roots broke up the soil so water could reach the cucumbers more easily?",
      "They tried it together. They moved soil, repositioned plants, and shared what little water they had equally.",
      "By the end of summer, both gardens were the most productive they had ever been.",
      "Their parents stood looking at the harvest in amazement. Maya's mother said quietly: They did better together than we ever did apart.",
      "Maya and Rowan smiled at each other across the fence and understood what the garden had been showing them all along: when you help someone else grow, you always grow too.",
    ],
  },
  {
    id: "4",
    lang: "en",
    titleEn: "The Star Keeper's Question",
    emoji: "🔭",
    moral: "Questions are the beginning of every great discovery.",
    sentences: [
      "Nora could not sleep. Every night she lay in bed staring at the ceiling, full of questions she could not stop thinking about.",
      "One night her father found her at the window with her face pressed against the glass, looking up at the sky.",
      "What are you looking at? he asked.",
      "The stars, she said. I want to know how far away they are. And whether there are people on them. And what is beyond the very last star.",
      "Her father sat beside her and said: Those are very good questions. Even the best scientists in the world have not answered all of them yet.",
      "Nora frowned and said: But scientists know so many things already. Like that light takes eight minutes to travel from the sun to Earth. And that the universe is fourteen billion years old.",
      "Yes, said her father. And all of that started with someone exactly like you, sitting in the dark, looking up, and asking: I wonder why. I wonder how.",
      "Nora thought about that for a long, quiet moment.",
      "Then she asked: So my questions are not silly?",
      "Her father said gently: Your questions are exactly the right size. Questions are the beginning of every great discovery.",
      "That night, Nora started a notebook. On the first page she wrote: Things I want to understand. And she filled the first page completely before she fell asleep.",
      "She grew up to become a scientist who studied distant galaxies. On her first published paper, she wrote in the dedication: To every child who ever stared at the sky and wondered.",
      "And every single night before sleep, she still asked one more question — because she knew that was exactly where everything important begins.",
    ],
  },
  {
    id: "5",
    lang: "en",
    titleEn: "The Last Bee",
    emoji: "🐝",
    moral: "Every living creature holds the world together — and every single one deserves a place to belong.",
    sentences: [
      "One warm spring morning, Amira noticed that the apple tree in her grandfather's orchard had not bloomed for two years in a row.",
      "Her grandfather said with a sad voice: There are no more bees here, Amira. Without bees, the flowers cannot become fruit.",
      "Where did they go? she asked.",
      "He sighed. When people use too many chemicals, when wildflowers disappear, when there is no safe place left for bees to nest — they leave. Or they die.",
      "Amira stood very still, thinking. Then she said quietly: We have to bring them back.",
      "She went to the library and researched what bees need: wildflowers, clean water, and small patches of bare earth to nest in. No chemicals. Just nature.",
      "She asked her grandfather to let her plant one corner of the orchard with lavender, clover, and sunflowers. He agreed.",
      "She also built two small bee hotels from bamboo sticks and pinecones, exactly the way a library book had shown her.",
      "She watered the flowers carefully every day through a dry spring and a long, hot summer.",
      "In late summer, the first bee arrived. Then three more. Then a small colony discovered the corner of the orchard and decided to stay.",
      "The following spring, for the first time in two years, the apple tree burst into white blossoms, beautiful and full.",
      "Her grandfather stood under the blossoming tree with tears in his eyes. You brought it back, he said softly.",
      "Amira watched the bees moving busily from flower to flower and understood something she would never forget: every living creature holds the world together — and every single one deserves a place to belong.",
    ],
  },
  {
    id: "6",
    lang: "en",
    titleEn: "The Boy Who Never Stopped",
    emoji: "⚙️",
    moral: "Patience opens every locked door.",
    sentences: [
      "Yusuf was eight years old and loved inventing things from old wood and broken wires.",
      "His biggest dream was to build a small fan that worked without electricity.",
      "Every day after school, he sat in the garden with a box of materials: wood pieces, spools of thread, and empty bottles.",
      "The first attempt failed. So did the second. And the third. And the fourth.",
      "His friends told him once: This is impossible, Yusuf. Just give up!",
      "But Yusuf smiled and said: Every time I fail, I learn something new that I did not know before.",
      "On his ninth attempt, he changed the shape of the blades and added a small weight in the center.",
      "When he held it up and released it into the air, it spun slowly — then faster — then flew!",
      "Yusuf shouted with joy so loudly that the neighbors heard, and his father ran into the garden to see what had happened.",
      "His father said proudly: You did not succeed on the first try. You succeeded on the ninth. That is the real value of patience.",
      "That night, Yusuf wrote in his notebook in the biggest letters he could: Patience opens every locked door.",
      "When he grew up, he became an engineer who invented things that helped thousands of children in his country.",
      "And every invention in his life started the same way: an idea, a failure, and a return to try again.",
    ],
  },
  {
    id: "7",
    lang: "en",
    titleEn: "The Seed of Hope",
    emoji: "🌱",
    moral: "Every great thing began as something very small.",
    sentences: [
      "On a very hot day, Sara found a tiny seed in the heart of a dry and barren patch of land.",
      "Her older sister said: This ground is dead, Sara. Nothing will grow here.",
      "But Sara carefully carried the seed and planted it with her small hands near an old stream.",
      "Every morning, before school, she brought a cup of water and quietly gave the seed a drink.",
      "Three full weeks passed with no sign of growth.",
      "Sara cried for just one day — then said: Maybe the seed just needs more time.",
      "In the fourth week, something small and green pushed gently through the soil.",
      "Each day it grew more, until it became a small bush casting a gentle shadow over the ground.",
      "The birds came first. Then the butterflies. Then the children, sitting in its shade.",
      "Her older sister said in amazement: I was completely wrong, Sara.",
      "Sara smiled and said: The ground was not dead. It was just waiting for someone who believed in it.",
      "And Sara learned that day a lesson she never forgot:",
      "Every great thing in this world began as something very small — and a heart that refuses to give up.",
    ],
  },
  {
    id: "8",
    lang: "en",
    titleEn: "The Village Without Rain",
    emoji: "💧",
    moral: "Kindness multiplies when you share it.",
    sentences: [
      "For three summers in a row, no rain fell on the small mountain village of Briar.",
      "The well ran dry. The gardens turned to dust. And the people grew worried and quiet.",
      "A young girl named Elara decided she would not wait for rain. She would find water.",
      "She climbed the rocky hills every day for a week, following the path of dry river beds and cracked earth.",
      "High up in the hills, behind a wall of stone, she discovered a hidden spring — cold, clear, and full.",
      "But the spring was too far for the villagers to carry water every day.",
      "Elara thought carefully. She built a small channel from stones and clay — just a tiny one, barely as wide as her hand.",
      "She worked every morning for two weeks, adding stones, sealing gaps, guiding the water down the hillside.",
      "The first trickle reached the village on a Tuesday afternoon.",
      "By the end of the week, a steady stream flowed into the dry well, and it began slowly to fill.",
      "The villagers gathered around in silence — and then erupted in cheering so loud the birds flew from the trees.",
      "The elder held Elara's hands and asked: How did you do this?",
      "She said simply: I did not do it alone. The hill had the spring. The stones made the path. I just believed the water wanted to reach us.",
      "And that year, the gardens of Briar bloomed more beautifully than anyone could remember.",
    ],
  },
  {
    id: "9",
    lang: "en",
    titleEn: "The Library That No One Used",
    emoji: "📚",
    moral: "A reader lives a hundred lives. A person who never reads lives only one.",
    sentences: [
      "At the end of a small street stood a library that no one visited anymore.",
      "The shelves were full of books. The lights still worked. But the chairs were always empty.",
      "A boy named Finn walked past it every day and always looked away — books seemed boring and old.",
      "One rainy afternoon, with nowhere else to go, he pushed open the heavy door and stepped inside.",
      "The librarian looked up from behind a tall stack of books and said: Welcome. What do you love?",
      "Finn shrugged. Nothing, he said.",
      "The librarian was quiet for a moment. Then she walked across the room and placed a single book in his hands.",
      "This one, she said. Just read the first page.",
      "Finn read the first page. Then the second. Then he sat down without noticing he was sitting.",
      "Two hours later, he was still reading — in a story about a boy who discovered a secret island full of animals that could speak.",
      "When he finally looked up, the rain had stopped, the sun was low, and the library was about to close.",
      "He borrowed the book and came back the next day — and the day after that.",
      "By the end of the year, Finn had read thirty-one books. He started a reading club at his school.",
      "Twelve children joined. Then twenty-five. The library chairs were never empty again.",
      "Finn learned that a reader lives a hundred lives — and a person who never reads lives only one.",
    ],
  },
  {
    id: "10",
    lang: "en",
    titleEn: "The Youngest Inventor",
    emoji: "🔬",
    moral: "Age is never a reason not to try.",
    sentences: [
      "At just nine years old, Zara decided she was going to invent something that would help people.",
      "She did not know what yet. She just knew she had to try.",
      "She started carrying a notebook everywhere — to school, to the park, to the dinner table.",
      "Whenever she saw a problem, she wrote it down. A broken streetlight. A slippery ramp at the library. A garden hose that kept kinking.",
      "Her list grew to fifty-three problems before she found the one that felt right.",
      "The problem: her grandmother's arthritis made it painful to open medicine bottles every morning.",
      "Zara spent four months designing a simple handle that could be attached to any bottle cap, making it easier to grip and turn.",
      "She used cardboard, then rubber, then a combination of both — testing and failing and adjusting every week.",
      "She entered her invention in the school science fair — the youngest participant by three years.",
      "The judges asked her: How did a nine-year-old come up with this?",
      "She said: My grandmother needed it. That was enough reason.",
      "Zara did not win first place. She won second. But she was already working on version two of her design before she got home.",
      "Her grandmother wore the handle every morning and said: You solved the hardest part of my day.",
      "And Zara understood at last what she had suspected all along: age is never a reason not to try.",
    ],
  },
  {
    id: "11",
    lang: "en",
    titleEn: "The Robot Who Learned to Cry",
    emoji: "🤖",
    moral: "Feelings are bridges between people — never be ashamed of yours.",
    sentences: [
      "Sana was ten years old and loved building things more than anything in the world.",
      "One summer, she built a small robot from an old tin box, two clock gears, and a blinking blue LED for an eye.",
      "She called him Nour, which means light, because he lit up whenever she walked into the room.",
      "Nour could not talk or walk, but he could beep — once for yes, twice for no — and Sana understood him perfectly.",
      "One afternoon, Sana's grandmother came to visit. She had been very ill, and she looked tired and thin.",
      "Nour's blue LED flickered three times in a slow, strange rhythm that Sana had never seen before.",
      "She watched him carefully. His light dimmed, then blinked again — slowly, like someone trying very hard not to cry.",
      "Sana sat on the floor beside him and said quietly: I know, Nour. I am sad too.",
      "She had programmed him to blink faster when something good happened and slower when something did not.",
      "But this was the first time she realized: the machine had learned to notice sadness from watching her.",
      "Her grandmother leaned down and touched the little robot gently. She said: He has your heart, Sana.",
      "Sana smiled through her own tears and understood something she would never forget: when you build with love, love finds a way to live in what you make.",
    ],
  },
  {
    id: "12",
    lang: "en",
    titleEn: "The Compass That Never Lied",
    emoji: "🧭",
    moral: "Honesty is your compass — it always points you home.",
    sentences: [
      "Malik was nine years old when his grandfather gave him a small brass compass with a cracked glass face.",
      "It belonged to your great-great-grandfather, said his grandfather. He carried it across three deserts. It never lied.",
      "Malik looked at the needle. It always pointed north — steady and still, no matter how he turned the compass.",
      "One winter afternoon, Malik and his grandfather hiked into the hills behind their town and got turned around in the fog.",
      "His grandfather said: Look at the compass. Tell me which way is north.",
      "Malik squinted at the needle. North is that way, he said — pointing toward a path that looked like it went deeper into the hills.",
      "His grandfather looked worried. Are you sure? The road to town should be the other way.",
      "Malik looked again. He did not change his answer. I am sure. The compass says north, and our town is south of these hills.",
      "His grandfather nodded slowly. Then let us trust it.",
      "They walked south for twenty minutes — and there was the road, exactly where the compass had promised.",
      "Walking home in the warm lamplight, his grandfather said: The compass is like honesty. When everything around you is foggy and confusing, it always tells you exactly where you are.",
      "Malik held the compass tightly and understood: honesty is never the easy direction — but it is always the right one.",
    ],
  },
  {
    id: "13",
    lang: "en",
    titleEn: "The Dragon Who Was Afraid of the Dark",
    emoji: "🐉",
    moral: "Everyone has fears. True courage is facing them together.",
    sentences: [
      "Everyone knew that dragons breathe fire — but what no one knew was that Ember, the smallest dragon on the mountain, was terrified of the dark.",
      "Every night when the other dragons put out their flames and slept, Ember kept his burning very low so the others thought he was just cold.",
      "One evening, a great storm came and blew out every flame on the mountain — including Ember's.",
      "He sat in the dark, trembling, wings wrapped tightly around himself.",
      "From somewhere nearby, a small voice said: Me too.",
      "Ember looked around. Beside him sat a fox kit, shaking just as hard.",
      "They stayed there together through the long storm — neither able to see much, both afraid, but neither quite as afraid as they had been alone.",
      "When the storm finally passed and the morning light came creeping in, Ember lit his flame again and warmed them both.",
      "The fox said: How did you do that? You were scared too.",
      "Ember said: I was scared. But you were scared too, and that made me feel brave enough to try.",
      "And from that night on, Ember understood something no one had ever taught him in dragon school: everyone has fears, and the bravest thing you can ever do is face them side by side with someone who feels the same.",
    ],
  },
  {
    id: "14",
    lang: "en",
    titleEn: "The Boy Who Asked a Million Questions",
    emoji: "❓",
    moral: "Curiosity is the engine of every great discovery.",
    sentences: [
      "Omar asked questions the way other children breathed — constantly, without thinking, and impossible to stop.",
      "Why is the sky blue? Why do cats purr? What is inside a second? Where does a thought come from?",
      "His teachers answered the first hundred questions patiently.",
      "By question three hundred and forty-one, some of them began to look a little tired.",
      "But one teacher, who had white hair and ink-stained fingers, always smiled and said: That is the most important question you have asked yet.",
      "One day Omar asked: Why do bridges stay up?",
      "Together, he and the teacher spent an hour drawing arches and looking at photos of ancient Roman bridges still standing after two thousand years.",
      "Omar went home and built a small bridge from popsicle sticks. He tested it with a pile of books. It held seventeen.",
      "He wrote in his notebook: A bridge holds up because the weight is shared. Like a good team.",
      "The white-haired teacher found that notebook years later, when Omar had grown up and was designing real bridges for a living.",
      "She read the first page and smiled: curiosity is not a problem to be managed — it is an engine waiting for fuel.",
      "And Omar, who had asked a million questions, built things that would last a hundred years — each one beginning with the simplest question of all: Why?",
    ],
  },
  {
    id: "15",
    lang: "en",
    titleEn: "The Painter Who Mixed Colors",
    emoji: "🎨",
    moral: "Our differences, mixed together, make something more beautiful than any one thing alone.",
    sentences: [
      "Lena lived in a town where everyone believed that the most beautiful color was white — pure, clean, and simple.",
      "Every wall in town was white. Every door, every fence, every flower pot — white.",
      "Lena was a painter who had been given one gift she did not ask for: she could see every color, more colors than most people even have names for.",
      "She did not show anyone what she painted, because she worried it was too much — too bright, too mixed, too different.",
      "One winter, a long storm left the town grey and heavy for seven days straight.",
      "On the eighth day, Lena could not stand it anymore. She went out with all her paints and started painting the wall of the empty bakery.",
      "She mixed purple into orange. She layered yellow over green. She drew spirals of blue beside warm rose.",
      "By evening, the whole wall was a garden of impossible, joyful colors.",
      "People gathered slowly. Some were unsure. Some gasped. A small boy pressed his hand flat against the wall and said: It feels warm.",
      "Lena smiled and told him the secret she had kept for years: every color you see here was made by mixing two colors that people once thought could not go together.",
      "And every single one became more beautiful because of it.",
    ],
  },
  {
    id: "16",
    lang: "en",
    titleEn: "The Smallest Library",
    emoji: "📖",
    moral: "When you share what you know, everyone becomes richer.",
    sentences: [
      "Tariq lived on a street where the closest library was three bus rides away — which meant most children on his street never went.",
      "He had twenty-three books of his own and had read every single one of them at least twice.",
      "One afternoon, he put a wooden crate outside his front door with a handwritten sign: Take a book. Leave a book.",
      "No one took anything on the first day.",
      "On the second day, a girl named Rosa took a book about penguins and left one about volcanoes.",
      "By the end of the week, twelve books had moved in and twelve had moved out.",
      "By the end of the month, neighbors were leaving chairs outside. Then a rug. Then someone brought a lamp.",
      "By summer, it had become something between a library and a living room — open to everyone on the street, day or evening.",
      "A journalist came and took a photo. She asked Tariq: How did you build all this?",
      "He said honestly: I did not build it. I just left a crate outside my door.",
      "She shook her head and said: You started something. And starting is always the hardest part.",
      "Tariq looked at the shelves built by his neighbors from old wooden pallets and understood: when you share what you know, the world around you grows — and so do you.",
    ],
  },
  {
    id: "17",
    lang: "en",
    titleEn: "One Step at a Time",
    emoji: "🏔️",
    moral: "You do not have to move the mountain all at once. One step today is enough.",
    sentences: [
      "At the edge of Mira's village stood a mountain so tall that no one from her village had ever reached the top.",
      "People said it was too steep, too cold, too far.",
      "Mira was eleven years old, and she said simply: I am going to climb it.",
      "Her uncle laughed kindly. That mountain is too much for you, little one.",
      "Mira did not argue. She put on her boots and started walking.",
      "On the first day, she reached the forest at the base. That was enough for that day.",
      "On the second, she reached the first rocky slope. She sat, breathed the cool air, and came back down.",
      "Each day she went a little further. Each day the mountain gave her a little more.",
      "On the fourteenth day, she reached the very top.",
      "The view was everything she had imagined and more: her village, small and golden below her, the whole valley spread out like a painting.",
      "She sat at the summit and wrote three words in the thin frost with her finger: One step today.",
      "Then she stood up and began the long walk home — already planning what she would climb next.",
    ],
  },
  {
    id: "18",
    lang: "en",
    titleEn: "The Echo in the Valley",
    emoji: "🏞️",
    moral: "Whatever you send out into the world comes back to you.",
    sentences: [
      "High in the mountains lived a boy named Casim, who had a strange habit that his family found amusing.",
      "Every morning, he walked to the edge of the valley and shouted something — and then stood very still to listen to the echo.",
      "On angry days, he shouted: The world is unfair! And it rolled back: unfair… unfair… unfair…",
      "On good days, he shouted: Today is going to be amazing! And it came back: amazing… amazing… amazing…",
      "One spring morning, his little sister followed him to the valley edge and asked: Why do you always shout things out here?",
      "Casim said: To remind myself that what I put out always comes back.",
      "She frowned. That is just how sound works.",
      "He smiled. Yes. And it is how people work too.",
      "She thought about that for a long, quiet time.",
      "That afternoon, she did something she had been putting off: she apologized to a friend she had argued with.",
      "When her friend smiled back warmly and said: I missed you, she understood exactly what her brother had meant — not the sound, but the feeling.",
      "Whatever you send out into the world, in one form or another, finds its way back to you.",
    ],
  },
  {
    id: "19",
    lang: "en",
    titleEn: "The Scientist Who Failed for Forty Years",
    emoji: "🌹",
    moral: "Failure is not the opposite of success — it is the path to it.",
    sentences: [
      "Professor Anya had spent forty years trying to grow a rose that bloomed in winter.",
      "Every year she planted. Every year the frost came and the petals fell.",
      "Her students asked her once: Professor, why do you keep trying? You have failed every year for forty years.",
      "She said quietly: I have not failed forty times. I have discovered forty things that do not work. That is very different.",
      "In her forty-first year, she made one small change: she added a layer of volcanic mineral to the soil before the frost arrived.",
      "In January, on a morning so cold that ice covered every window, she walked into her greenhouse.",
      "One rose had bloomed — a single deep red flower, perfect and completely still.",
      "She stood looking at it for a long, quiet moment without moving.",
      "Her assistant came in and said breathlessly: Professor. You did it.",
      "She nodded slowly and said: We did it. The forty years of failure taught me everything I needed to know to finally get it right.",
      "She called the rose Winter's Answer — and it became one of the most studied flowers in the history of botany.",
      "And in every class she taught from that day forward, she began with the same sentence: Before you show me your successes, show me your beautiful failures.",
    ],
  },
  {
    id: "20",
    lang: "en",
    titleEn: "The Child Who Fixed the Clock",
    emoji: "⏰",
    moral: "Time is the only thing you cannot get back — choose how you use it.",
    sentences: [
      "Rena was twelve years old when her grandfather's old clock stopped working.",
      "She opened the back of it very carefully and found hundreds of tiny gears, springs, and pins — a whole world of moving pieces, all balanced and counting.",
      "She asked her grandfather: What does a clock actually do?",
      "He said: It measures the only thing that never comes back.",
      "Rena spent three weeks taking the clock apart, drawing every piece in a notebook, and slowly putting it back together.",
      "On the eighteenth day, she wound the spring — and the clock began to tick again.",
      "The sound of it filled the quiet room. Her grandfather pressed his hand gently to his heart.",
      "Rena asked him: What were you thinking just now?",
      "He said: About all the hours in that clock that I wasted being afraid, or angry, or waiting for things to be different. Time you cannot get back.",
      "Rena held the clock carefully and thought about all the things she still wanted to do, make, learn, and become.",
      "From that day on, she never let a good hour pass without purpose — not every hour had to be busy, but every hour was chosen.",
      "Because she had learned that time is the only clock that cannot be rewound.",
    ],
  },
];
