export type Story = {
  id: string;
  lang: "en";
  titleEn: string;
  emoji: string;
  moral: string;
  sentences: string[];
};

export const STORIES: Story[] = [
  {
    id: "1",
    lang: "en",
    titleEn: "The Girl Who Never Stopped Trying",
    emoji: "💡",
    moral: "Every mistake is a step closer to your answer.",
    sentences: [
      "Layla was eight years old, and she had one big dream: to make a light bulb glow using only a lemon from her grandmother's garden.",
      "Every afternoon after school, she spread her notebook on the kitchen table, lined up her copper clips and wires, and placed three lemons in a row.",
      "Her first experiment failed completely. The bulb stayed cold and dark no matter how many times she checked.",
      "She wrote in her notebook: Experiment one — did not work. The wire was too thin. Tomorrow I will try something thicker.",
      "Her second try failed. So did her third and her fourth.",
      "Her older brother came in and said: Give up, Layla. Lemons are for lemonade, not for science!",
      "Layla looked at her notes calmly and said: Thomas Edison failed more than a thousand times before he made the light bulb. I have only failed four times.",
      "On her seventh experiment, she pressed a copper coin and a zinc clip into the lemon, connected the wires very carefully, and held her breath.",
      "A tiny, soft golden light blinked on.",
      "Layla sat very still for a long moment — then laughed so loudly that her mother came running from the next room.",
      "Her mother held Layla's face gently and said: You did not succeed because you were clever. You succeeded because you refused to stop.",
      "That night, Layla wrote on the very last page of her notebook in the biggest letters she could: Every mistake is a step closer to your answer.",
      "She kept learning — about batteries, circuits, and solar energy. She won three science competitions.",
      "Many years later, Layla led a team of engineers who brought electricity to twelve villages in the desert, where children finally did their homework under electric light — and on her desk, she always kept that small lemon notebook.",
    ],
  },
  {
    id: "2",
    lang: "en",
    titleEn: "The Boy Who Talked to Trees",
    emoji: "🌳",
    moral: "The earth is always listening. Protect what you love before it is gone.",
    sentences: [
      "Idris was ten years old and had a habit that made his classmates laugh: he talked to trees.",
      "Every morning on his way to school, he stopped at the oldest oak in the neighborhood, placed his hand on its bark, and said: Good morning. Are you growing today?",
      "His friends thought it was silly. Trees cannot hear you, they said.",
      "But Idris had read that plants respond to sound and vibration, and he believed that listening — even to something that cannot speak back — was a form of respect.",
      "One spring, the city decided to cut down the old oak tree to widen the road.",
      "Idris felt something break inside him. That tree had stood in that spot for more than sixty years.",
      "He did not shout or cry. Instead, he went home and wrote a careful letter to the city council, full of facts about how trees clean the air, cool streets, and protect neighborhoods from floods.",
      "He collected forty-three signatures from neighbors and asked his teacher to help him present the letter at a local meeting.",
      "The council listened carefully. They decided to reroute the road and spare the tree.",
      "The old oak still stands today, with a small sign beside it that reads: Protected by the community.",
      "Idris's mother asked him: How did you know what to do?",
      "He said: I learned it from the tree. It stood there for sixty years, quietly giving shade and clean air to everyone, without ever asking for anything. I just tried to do the same.",
      "And that day, Idris understood something he would carry his whole life: the earth is always listening — and it is up to us to listen back.",
    ],
  },
  {
    id: "3",
    lang: "en",
    titleEn: "Two Seeds in the Same Garden",
    emoji: "🤝",
    moral: "When you help someone else grow, you always grow too.",
    sentences: [
      "Maya and Rowan were neighbors and best friends, but they argued about one thing: whose garden vegetables grew better.",
      "Maya's family planted tomatoes, and Rowan's family planted cucumbers, and every summer both families competed to grow the most beautiful harvest.",
      "One summer, a long dry spell hit their neighborhood. The sun beat down without mercy, and the wells ran low.",
      "Maya's tomato plants began to wilt. Rowan's cucumber plants also struggled to survive.",
      "One afternoon, both children sat at the fence between their gardens, feeling defeated.",
      "Rowan said: My cucumbers need shade. The sun is burning them.",
      "Maya said: My tomatoes need more water. The soil dries out too fast.",
      "They looked at each other — and then, at exactly the same time, they both had the same idea.",
      "What if the cucumber vines climbed Maya's fence and gave shade to the tomatoes? And what if the tomato roots broke up the soil so water could reach the cucumbers more easily?",
      "They tried it together. They moved soil, repositioned plants, and shared what little water they had equally.",
      "By the end of summer, both gardens were the most productive they had ever been.",
      "Their parents stood looking at the harvest in amazement. Maya's mother said quietly: They did better together than we ever did apart.",
      "Maya and Rowan smiled at each other across the fence and understood what the garden had been showing them all along: when you help someone else grow, you always grow too.",
    ],
  },
  {
    id: "4",
    lang: "en",
    titleEn: "The Star Keeper's Question",
    emoji: "🔭",
    moral: "Questions are the beginning of every great discovery.",
    sentences: [
      "Nora could not sleep. Every night she lay in bed staring at the ceiling, full of questions she could not stop thinking about.",
      "One night her father found her at the window with her face pressed against the glass, looking up at the sky.",
      "What are you looking at? he asked.",
      "The stars, she said. I want to know how far away they are. And whether there are people on them. And what is beyond the very last star.",
      "Her father sat beside her and said: Those are very good questions. Even the best scientists in the world have not answered all of them yet.",
      "Nora frowned and said: But scientists know so many things already. Like that light takes eight minutes to travel from the sun to Earth. And that the universe is fourteen billion years old.",
      "Yes, said her father. And all of that started with someone exactly like you, sitting in the dark, looking up, and asking: I wonder why. I wonder how.",
      "Nora thought about that for a long, quiet moment.",
      "Then she asked: So my questions are not silly?",
      "Her father said gently: Your questions are exactly the right size. Questions are the beginning of every great discovery.",
      "That night, Nora started a notebook. On the first page she wrote: Things I want to understand. And she filled the first page completely before she fell asleep.",
      "She grew up to become a scientist who studied distant galaxies. On her first published paper, she wrote in the dedication: To every child who ever stared at the sky and wondered.",
      "And every single night before sleep, she still asked one more question — because she knew that was exactly where everything important begins.",
    ],
  },
  {
    id: "5",
    lang: "en",
    titleEn: "The Last Bee",
    emoji: "🐝",
    moral: "Every living creature holds the world together — and every single one deserves a place to belong.",
    sentences: [
      "One warm spring morning, Amira noticed that the apple tree in her grandfather's orchard had not bloomed for two years in a row.",
      "Her grandfather said with a sad voice: There are no more bees here, Amira. Without bees, the flowers cannot become fruit.",
      "Where did they go? she asked.",
      "He sighed. When people use too many chemicals, when wildflowers disappear, when there is no safe place left for bees to nest — they leave. Or they die.",
      "Amira stood very still, thinking. Then she said quietly: We have to bring them back.",
      "She went to the library and researched what bees need: wildflowers, clean water, and small patches of bare earth to nest in. No chemicals. Just nature.",
      "She asked her grandfather to let her plant one corner of the orchard with lavender, clover, and sunflowers. He agreed.",
      "She also built two small bee hotels from bamboo sticks and pinecones, exactly the way a library book had shown her.",
      "She watered the flowers carefully every day through a dry spring and a long, hot summer.",
      "In late summer, the first bee arrived. Then three more. Then a small colony discovered the corner of the orchard and decided to stay.",
      "The following spring, for the first time in two years, the apple tree burst into white blossoms, beautiful and full.",
      "Her grandfather stood under the blossoming tree with tears in his eyes. You brought it back, he said softly.",
      "Amira watched the bees moving busily from flower to flower and understood something she would never forget: every living creature holds the world together — and every single one deserves a place to belong.",
    ],
  },
  {
    id: "6",
    lang: "en",
    titleEn: "The Boy Who Never Stopped",
    emoji: "⚙️",
    moral: "Patience opens every locked door.",
    sentences: [
      "Yusuf was eight years old and loved inventing things from old wood and broken wires.",
      "His biggest dream was to build a small fan that worked without electricity.",
      "Every day after school, he sat in the garden with a box of materials: wood pieces, spools of thread, and empty bottles.",
      "The first attempt failed. So did the second. And the third. And the fourth.",
      "His friends told him once: This is impossible, Yusuf. Just give up!",
      "But Yusuf smiled and said: Every time I fail, I learn something new that I did not know before.",
      "On his ninth attempt, he changed the shape of the blades and added a small weight in the center.",
      "When he held it up and released it into the air, it spun slowly — then faster — then flew!",
      "Yusuf shouted with joy so loudly that the neighbors heard, and his father ran into the garden to see what had happened.",
      "His father said proudly: You did not succeed on the first try. You succeeded on the ninth. That is the real value of patience.",
      "That night, Yusuf wrote in his notebook in the biggest letters he could: Patience opens every locked door.",
      "When he grew up, he became an engineer who invented things that helped thousands of children in his country.",
      "And every invention in his life started the same way: an idea, a failure, and a return to try again.",
    ],
  },
  {
    id: "7",
    lang: "en",
    titleEn: "The Seed of Hope",
    emoji: "🌱",
    moral: "Every great thing began as something very small.",
    sentences: [
      "On a very hot day, Sara found a tiny seed in the heart of a dry and barren patch of land.",
      "Her older sister said: This ground is dead, Sara. Nothing will grow here.",
      "But Sara carefully carried the seed and planted it with her small hands near an old stream.",
      "Every morning, before school, she brought a cup of water and quietly gave the seed a drink.",
      "Three full weeks passed with no sign of growth.",
      "Sara cried for just one day — then said: Maybe the seed just needs more time.",
      "In the fourth week, something small and green pushed gently through the soil.",
      "Each day it grew more, until it became a small bush casting a gentle shadow over the ground.",
      "The birds came first. Then the butterflies. Then the children, sitting in its shade.",
      "Her older sister said in amazement: I was completely wrong, Sara.",
      "Sara smiled and said: The ground was not dead. It was just waiting for someone who believed in it.",
      "And Sara learned that day a lesson she never forgot:",
      "Every great thing in this world began as something very small — and a heart that refuses to give up.",
    ],
  },
  {
    id: "8",
    lang: "en",
    titleEn: "The Village Without Rain",
    emoji: "💧",
    moral: "Kindness multiplies when you share it.",
    sentences: [
      "For three summers in a row, no rain fell on the small mountain village of Briar.",
      "The well ran dry. The gardens turned to dust. And the people grew worried and quiet.",
      "A young girl named Elara decided she would not wait for rain. She would find water.",
      "She climbed the rocky hills every day for a week, following the path of dry river beds and cracked earth.",
      "High up in the hills, behind a wall of stone, she discovered a hidden spring — cold, clear, and full.",
      "But the spring was too far for the villagers to carry water every day.",
      "Elara thought carefully. She built a small channel from stones and clay — just a tiny one, barely as wide as her hand.",
      "She worked every morning for two weeks, adding stones, sealing gaps, guiding the water down the hillside.",
      "The first trickle reached the village on a Tuesday afternoon.",
      "By the end of the week, a steady stream flowed into the dry well, and it began slowly to fill.",
      "The villagers gathered around in silence — and then erupted in cheering so loud the birds flew from the trees.",
      "The elder held Elara's hands and asked: How did you do this?",
      "She said simply: I did not do it alone. The hill had the spring. The stones made the path. I just believed the water wanted to reach us.",
      "And that year, the gardens of Briar bloomed more beautifully than anyone could remember.",
    ],
  },
  {
    id: "9",
    lang: "en",
    titleEn: "The Library That No One Used",
    emoji: "📚",
    moral: "A reader lives a hundred lives. A person who never reads lives only one.",
    sentences: [
      "At the end of a small street stood a library that no one visited anymore.",
      "The shelves were full of books. The lights still worked. But the chairs were always empty.",
      "A boy named Finn walked past it every day and always looked away — books seemed boring and old.",
      "One rainy afternoon, with nowhere else to go, he pushed open the heavy door and stepped inside.",
      "The librarian looked up from behind a tall stack of books and said: Welcome. What do you love?",
      "Finn shrugged. Nothing, he said.",
      "The librarian was quiet for a moment. Then she walked across the room and placed a single book in his hands.",
      "This one, she said. Just read the first page.",
      "Finn read the first page. Then the second. Then he sat down without noticing he was sitting.",
      "Two hours later, he was still reading — in a story about a boy who discovered a secret island full of animals that could speak.",
      "When he finally looked up, the rain had stopped, the sun was low, and the library was about to close.",
      "He borrowed the book and came back the next day — and the day after that.",
      "By the end of the year, Finn had read thirty-one books. He started a reading club at his school.",
      "Twelve children joined. Then twenty-five. The library chairs were never empty again.",
      "Finn learned that a reader lives a hundred lives — and a person who never reads lives only one.",
    ],
  },
  {
    id: "10",
    lang: "en",
    titleEn: "The Youngest Inventor",
    emoji: "🔬",
    moral: "Age is never a reason not to try.",
    sentences: [
      "At just nine years old, Zara decided she was going to invent something that would help people.",
      "She did not know what yet. She just knew she had to try.",
      "She started carrying a notebook everywhere — to school, to the park, to the dinner table.",
      "Whenever she saw a problem, she wrote it down. A broken streetlight. A slippery ramp at the library. A garden hose that kept kinking.",
      "Her list grew to fifty-three problems before she found the one that felt right.",
      "The problem: her grandmother's arthritis made it painful to open medicine bottles every morning.",
      "Zara spent four months designing a simple handle that could be attached to any bottle cap, making it easier to grip and turn.",
      "She used cardboard, then rubber, then a combination of both — testing and failing and adjusting every week.",
      "She entered her invention in the school science fair — the youngest participant by three years.",
      "The judges asked her: How did a nine-year-old come up with this?",
      "She said: My grandmother needed it. That was enough reason.",
      "Zara did not win first place. She won second. But she was already working on version two of her design before she got home.",
      "Her grandmother wore the handle every morning and said: You solved the hardest part of my day.",
      "And Zara understood at last what she had suspected all along: age is never a reason not to try.",
    ],
  },
];
