export type Story = {
  id: string;
  lang: "en" | "ar";
  titleEn: string;
  titleAr: string;
  emoji: string;
  moral: { en: string; ar: string };
  sentences: string[];
};

export const STORIES: Story[] = [
  // ── Arabic Stories ──────────────────────────────────────────────────────────
  {
    id: "1",
    lang: "ar",
    titleEn: "The Boy Who Never Stopped",
    titleAr: "الولد الذي لم يتوقف",
    emoji: "⚙️",
    moral: { en: "Patience opens every locked door.", ar: "الصبر يفتح الأبواب المغلقة." },
    sentences: [
      "كان ياسر طفلاً في الثامنة من عمره، يعشق اختراع الأشياء من قطع الخشب والأسلاك القديمة.",
      "حلمه الكبير كان أن يصنع مروحة صغيرة تعمل بدون كهرباء.",
      "كل يوم بعد المدرسة، جلس في الحديقة أمامه صندوق المواد: قطع خشب، وبكرات خيط، وزجاجات فارغة.",
      "المحاولة الأولى فشلت. والثانية. والثالثة. والرابعة.",
      "قال له أصدقاؤه ذات مرة: هذا مستحيل يا ياسر. استسلم!",
      "لكن ياسر ابتسم وقال: كل مرة أفشل فيها، أتعلم شيئاً جديداً لم أكن أعرفه.",
      "في المحاولة التاسعة، غيّر شكل الأجنحة وأضاف ثقلاً صغيراً في المركز.",
      "حين أمسك بها وأطلقها في الهواء، دارت ببطء، ثم بسرعة أكبر، ثم طارت!",
      "صاح ياسر بفرح حتى سمعه الجيران، وركض أبوه إلى الحديقة ليرى ما حدث.",
      "قال أبوه بفخر: أنت لم تنجح في المحاولة الأولى، نجحت في التاسعة. هذه هي قيمة الصبر الحقيقية.",
      "في تلك الليلة، كتب ياسر في دفتره بأكبر خط يستطيع: الصبر يفتح الأبواب المغلقة.",
      "وعندما كبر، أصبح مهندساً اخترع أشياء ساعدت آلاف الأطفال في بلده.",
      "وكل اختراع في حياته بدأ بنفس الطريقة: فكرة، وفشل، وعودة من جديد.",
    ],
  },
  {
    id: "2",
    lang: "ar",
    titleEn: "The Seed of Hope",
    titleAr: "بذرة الأمل",
    emoji: "🌱",
    moral: { en: "Every great thing began as something very small.", ar: "كل شيء عظيم بدأ بشيء صغير جداً." },
    sentences: [
      "في يوم حار جداً، وجدت سارة بذرة صغيرة في قلب أرض جافة وقاحلة.",
      "قالت لها أختها الكبيرة: هذه الأرض ميتة يا سارة، لن ينبت فيها شيء.",
      "لكن سارة حملت البذرة بعناية، وزرعتها بيديها الصغيرتين في ركن قريب من مجرى ماء قديم.",
      "كل صباح، قبل المدرسة، جلبت كوباً من الماء وسقت البذرة بهدوء.",
      "مرت ثلاثة أسابيع كاملة بلا أي علامة على النمو.",
      "بكت سارة يوماً واحداً فقط، ثم قالت: ربما تحتاج البذرة وقتاً أطول.",
      "في الأسبوع الرابع، ظهر شيء أخضر صغير يشق التراب برفق.",
      "كل يوم كان ينمو أكثر، حتى أصبح شجيرة صغيرة تلقي ظلاً لطيفاً على الأرض.",
      "جاءت الطيور، ثم الفراشات، ثم الأطفال يجلسون في ظلها.",
      "قالت الأخت الكبيرة بدهشة: كنت مخطئة تماماً يا سارة.",
      "ابتسمت سارة وقالت: الأرض لم تكن ميتة يا أختي. كانت تنتظر من يصدق بها.",
      "وعلمت سارة في ذلك اليوم درساً لم تنسه طول حياتها:",
      "كل شيء عظيم في هذا العالم بدأ بشيء صغير جداً، وبقلب لا يستسلم.",
    ],
  },
  {
    id: "3",
    lang: "ar",
    titleEn: "The River and the Child",
    titleAr: "النهر والطفل",
    emoji: "🌊",
    moral: { en: "All it takes is one person to start — and the world follows.", ar: "يكفي أن تبدأ أنت لكي يتحرك العالم من حولك." },
    sentences: [
      "كان النهر الذي تحبه مريم يوماً مليئاً بالأسماك والأزهار والصوت الجميل.",
      "لكن في صيف عامها العاشر، لاحظت مريم أن قمامة كثيرة تراكمت على ضفته.",
      "الأسماك أصبحت قليلة، والطيور توقفت عن المجيء، والماء أصبح معتماً وحزيناً.",
      "قالت لأمها: النهر مريض يا أمي. ماذا يمكنني أن أفعل؟",
      "قالت أمها بحنان: أنت صغيرة يا مريم. ما الذي يستطيع طفل أن يفعله؟",
      "لم تقبل مريم هذه الإجابة.",
      "في صباح السبت التالي، جاءت بقفازات وأكياس وبدأت تنظف الضفة وحدها.",
      "بعد ساعة، انضم صديقها كريم. ثم جارتها ليلى. ثم والد كريم. ثم مزيد من الناس.",
      "بنهاية ذلك اليوم، كان هناك خمسة وعشرون شخصاً يعملون معاً بسعادة.",
      "في الأسبوع التالي، عادت أولى الطيور. وفي الشهر التالي، عادت الأسماك.",
      "قال والد كريم لمريم: أنتِ لم تنتظري أحداً يأذن لك بإصلاح ما كان مكسوراً.",
      "ابتسمت مريم ونظرت إلى النهر وهو يعود ليغني من جديد.",
      "وأدركت: يكفي أن تبدأ أنت لكي يتحرك العالم من حولك.",
    ],
  },
  {
    id: "4",
    lang: "ar",
    titleEn: "The Road of Stars",
    titleAr: "طريق النجوم",
    emoji: "🌌",
    moral: { en: "Curiosity is the first step toward every great discovery.", ar: "الفضول هو أول خطوة في كل اكتشاف عظيم." },
    sentences: [
      "كان تامر طفلاً لا ينام في الليل بسهولة، لأن رأسه كان دائماً مليئاً بالأسئلة.",
      "في ليلة صافية جميلة، جلس مع أمه على السطح ونظرا معاً إلى السماء.",
      "سأل تامر: أمي، كم عدد النجوم في السماء؟",
      "قالت أمه: هذا سؤال عظيم. حتى العلماء لا يعرفون الإجابة الكاملة.",
      "تعجب تامر: حتى العلماء؟",
      "قالت أمه: يقدّرون أن في مجرتنا وحدها أكثر من مئتي مليار نجم. والمجرات كثيرة جداً لا تُعد.",
      "شعر تامر بشيء غريب جميل في صدره، كأن العالم أكبر بكثير مما تخيّل.",
      "سأل: هل النجوم التي نراها موجودة الآن؟",
      "قالت أمه: ليس بالضرورة. الضوء يسافر سنوات طويلة ليصلنا. بعض النجوم التي نراها ماتت منذ آلاف السنين. أنت تنظر إلى الماضي.",
      "صمت تامر طويلاً وهو يفكر، ثم قال: أريد أن أكون عالماً يدرس النجوم.",
      "قالت أمه بابتسامة: إذن ابدأ الليلة. كل سؤال تسأله هو خطوة نحو ذلك.",
      "نام تامر تلك الليلة وهو يبتسم، وعيناه ما زالتا تريان النجوم.",
      "وعلم أن الفضول وحده هو أول خطوة في كل اكتشاف عظيم.",
    ],
  },
  {
    id: "5",
    lang: "ar",
    titleEn: "The Open Book",
    titleAr: "الكتاب المفتوح",
    emoji: "📖",
    moral: { en: "The words you read today shape the person you will become tomorrow.", ar: "الكلمات التي تقرأها اليوم تصنع الإنسان الذي ستصبحه غداً." },
    sentences: [
      "كان جد نور يجلس كل مساء في كرسيه القديم بجانب النافذة ويقرأ بهدوء.",
      "سألته نور وهي في السابعة من عمرها: جدي، لماذا تقرأ دائماً؟",
      "وضع الجد كتابه وابتسم لها.",
      "قال: لأن كل كتاب باب.",
      "قالت نور باهتمام: باب إلى أين؟",
      "قال: إلى أماكن لن تصلي إليها بقدميك. إلى أفكار لن تفكريها وحدك. إلى حكمة ناس عاشوا قبلنا بآلاف السنين وتركوها لنا هدية.",
      "أمسكت نور بكتاب صغير من الرف وبدأت تقرأ ببطء.",
      "بعد صفحات قليلة، نسيت الغرفة. نسيت الوقت. رأت الجبال والأنهار والشخصيات كأنها أمامها.",
      "حين أغلقت الكتاب، سألها جدها: أين كنتِ يا نور؟",
      "ضحكت وقالت: كنت في الجبال يا جدي!",
      "قال الجد بهدوء: هذا هو السر. القارئ لا يعيش حياة واحدة، يعيش مئات الحيوات.",
      "منذ تلك الليلة، أصبحت نور تقرأ كل يوم. في كل كتاب، فتحت باباً جديداً على عالم لم تكن تعرفه.",
      "وأدركت أن الكلمات التي تقرأها اليوم تصنع الإنسان الذي ستصبحه غداً.",
    ],
  },

  // ── English Stories ─────────────────────────────────────────────────────────
  {
    id: "6",
    lang: "en",
    titleEn: "The Girl Who Never Stopped Trying",
    titleAr: "الفتاة التي لم تتوقف أبداً",
    emoji: "💡",
    moral: { en: "Every mistake is a step closer to your answer.", ar: "كل خطأ هو خطوة نحو إجابتك." },
    sentences: [
      "Layla was eight years old, and she had one big dream: to make a light bulb glow using only a lemon from her grandmother's garden.",
      "Every afternoon after school, she spread her notebook on the kitchen table, lined up her copper clips and wires, and placed three lemons in a row.",
      "Her first experiment failed completely. The bulb stayed cold and dark no matter how many times she checked.",
      "She wrote in her notebook: Experiment one — did not work. The wire was too thin. Tomorrow I will try something thicker.",
      "Her second try failed. So did her third and her fourth.",
      "Her older brother came in and said: Give up, Layla. Lemons are for lemonade, not for science!",
      "Layla looked at her notes calmly and said: Thomas Edison failed more than a thousand times before he made the light bulb. I have only failed four times.",
      "On her seventh experiment, she pressed a copper coin and a zinc clip into the lemon, connected the wires very carefully, and held her breath.",
      "A tiny, soft golden light blinked on.",
      "Layla sat very still for a long moment — then laughed so loudly that her mother came running from the next room.",
      "Her mother held Layla's face gently and said: You did not succeed because you were clever. You succeeded because you refused to stop.",
      "That night, Layla wrote on the very last page of her notebook in the biggest letters she could: Every mistake is a step closer to your answer.",
      "She kept learning — about batteries, circuits, and solar energy. She won three science competitions.",
      "Many years later, Layla led a team of engineers who brought electricity to twelve villages in the desert, where children finally did their homework under electric light — and on her desk, she always kept that small lemon notebook to remind herself that great things never come easy, but everything worth doing is worth trying one more time.",
    ],
  },
  {
    id: "7",
    lang: "en",
    titleEn: "The Boy Who Talked to Trees",
    titleAr: "الولد الذي تحدث إلى الأشجار",
    emoji: "🌳",
    moral: { en: "The earth is always listening. Protect what you love before it is gone.", ar: "الأرض دائماً تسمع. احمِ ما تحبه قبل أن يرحل." },
    sentences: [
      "Idris was ten years old and had a habit that made his classmates laugh: he talked to trees.",
      "Every morning on his way to school, he stopped at the oldest oak in the neighborhood, placed his hand on its bark, and said: Good morning. Are you growing today?",
      "His friends thought it was silly. Trees cannot hear you, they said.",
      "But Idris had read that plants respond to sound and vibration, and he believed that listening — even to something that cannot speak back — was a form of respect.",
      "One spring, the city decided to cut down the old oak tree to widen the road.",
      "Idris felt something break inside him. That tree had stood in that spot for more than sixty years.",
      "He did not shout or cry. Instead, he went home and wrote a careful letter to the city council, full of facts about how trees clean the air, cool streets, and protect neighborhoods from floods.",
      "He collected forty-three signatures from neighbors and asked his teacher to help him present the letter at a local meeting.",
      "The council listened carefully. They decided to reroute the road and spare the tree.",
      "The old oak still stands today, with a small sign beside it that reads: Protected by the community.",
      "Idris's mother asked him: How did you know what to do?",
      "He said: I learned it from the tree. It stood there for sixty years, quietly giving shade and clean air to everyone, without ever asking for anything. I just tried to do the same.",
      "And that day, Idris understood something he would carry his whole life: the earth is always listening — and it is up to us to listen back.",
    ],
  },
  {
    id: "8",
    lang: "en",
    titleEn: "Two Seeds in the Same Garden",
    titleAr: "بذرتان في نفس الحديقة",
    emoji: "🤝",
    moral: { en: "When you help someone else grow, you always grow too.", ar: "حين تساعد الآخرين على النمو، أنت تنمو أيضاً." },
    sentences: [
      "Maya and Rowan were neighbors and best friends, but they argued about one thing: whose garden vegetables grew better.",
      "Maya's family planted tomatoes, and Rowan's family planted cucumbers, and every summer both families competed to grow the most beautiful harvest.",
      "One summer, a long dry spell hit their neighborhood. The sun beat down without mercy, and the wells ran low.",
      "Maya's tomato plants began to wilt. Rowan's cucumber plants also struggled to survive.",
      "One afternoon, both children sat at the fence between their gardens, feeling defeated.",
      "Rowan said: My cucumbers need shade. The sun is burning them.",
      "Maya said: My tomatoes need more water. The soil dries out too fast.",
      "They looked at each other — and then, at exactly the same time, they both had the same idea.",
      "What if the cucumber vines climbed Maya's fence and gave shade to the tomatoes? And what if the tomato roots broke up the soil so water could reach the cucumbers more easily?",
      "They tried it together. They moved soil, repositioned plants, and shared what little water they had equally.",
      "By the end of summer, both gardens were the most productive they had ever been.",
      "Their parents stood looking at the harvest in amazement. Maya's mother said quietly: They did better together than we ever did apart.",
      "Maya and Rowan smiled at each other across the fence and understood what the garden had been showing them all along: when you help someone else grow, you always grow too.",
    ],
  },
  {
    id: "9",
    lang: "en",
    titleEn: "The Star Keeper's Question",
    titleAr: "سؤال حارسة النجوم",
    emoji: "🔭",
    moral: { en: "Questions are the beginning of every great discovery.", ar: "الأسئلة هي بداية كل اكتشاف عظيم." },
    sentences: [
      "Nora could not sleep. Every night she lay in bed staring at the ceiling, full of questions she could not stop thinking about.",
      "One night her father found her at the window with her face pressed against the glass, looking up at the sky.",
      "What are you looking at? he asked.",
      "The stars, she said. I want to know how far away they are. And whether there are people on them. And what is beyond the very last star.",
      "Her father sat beside her and said: Those are very good questions. Even the best scientists in the world have not answered all of them yet.",
      "Nora frowned and said: But scientists know so many things already. Like that light takes eight minutes to travel from the sun to Earth. And that the universe is fourteen billion years old.",
      "Yes, said her father. And all of that started with someone exactly like you, sitting in the dark, looking up, and asking: I wonder why. I wonder how.",
      "Nora thought about that for a long, quiet moment.",
      "Then she asked: So my questions are not silly?",
      "Her father said gently: Your questions are exactly the right size. Questions are the beginning of every great discovery.",
      "That night, Nora started a notebook. On the first page she wrote: Things I want to understand. And she filled the first page completely before she fell asleep.",
      "She grew up to become a scientist who studied distant galaxies. On her first published paper, she wrote in the dedication: To every child who ever stared at the sky and wondered.",
      "And every single night before sleep, she still asked one more question — because she knew that was exactly where everything important begins.",
    ],
  },
  {
    id: "10",
    lang: "en",
    titleEn: "The Last Bee",
    titleAr: "آخر نحلة",
    emoji: "🐝",
    moral: { en: "Every living creature holds the world together — and every single one deserves a place to belong.", ar: "كل كائن حي يربط العالم معاً، وكل واحد منها يستحق مكاناً ينتمي إليه." },
    sentences: [
      "One warm spring morning, Amira noticed that the apple tree in her grandfather's orchard had not bloomed for two years in a row.",
      "Her grandfather said with a sad voice: There are no more bees here, Amira. Without bees, the flowers cannot become fruit.",
      "Where did they go? she asked.",
      "He sighed. When people use too many chemicals, when wildflowers disappear, when there is no safe place left for bees to nest — they leave. Or they die.",
      "Amira stood very still, thinking. Then she said quietly: We have to bring them back.",
      "She went to the library and researched what bees need: wildflowers, clean water, and small patches of bare earth to nest in. No chemicals. Just nature.",
      "She asked her grandfather to let her plant one corner of the orchard with lavender, clover, and sunflowers. He agreed.",
      "She also built two small bee hotels from bamboo sticks and pinecones, exactly the way a library book had shown her.",
      "She watered the flowers carefully every day through a dry spring and a long, hot summer.",
      "In late summer, the first bee arrived. Then three more. Then a small colony discovered the corner of the orchard and decided to stay.",
      "The following spring, for the first time in two years, the apple tree burst into white blossoms, beautiful and full.",
      "Her grandfather stood under the blossoming tree with tears in his eyes. You brought it back, he said softly.",
      "Amira watched the bees moving busily from flower to flower and understood something she would never forget: every living creature holds the world together — and every single one deserves a place to belong.",
    ],
  },
];
