// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/heroes/HeroCharacters.tsx": () => import("../components/mockups/heroes/HeroCharacters.tsx"),
  "./components/mockups/rive/RiveCharacter.tsx": () => import("../components/mockups/rive/RiveCharacter.tsx")
};
